### ISSUE TITLE
Rename and move settings.sh

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#10]
The base config file is historically named settings.sh and lives in the scripts folder.
Now combawa is what it is, this file should be named **.combawa** and live at the root of the project.

Bonus: as this is not a shell script anymore, its shebang should be dropped.

**Do not forget to bump version of the script with this change and do not forget to document it in the readme**

**Comment by DuaelFr** [comment]
New toughts: this should be called **.app** instead of .combawa and all generic env vars should also be prefixed by **APP_** instead of COMBAWA_ (except the ones that are only used by combawa and not Drupal).

**Comment by DuaelFr** [comment]
Decision: use **.combawa** and keep the envvars namespace.
Document the change!

**Comment by Artusamak** [comment]
The settings.sh file now leaves at the project root and is called .combawa.
