### ISSUE TITLE
Support UTF-8 chars for passwords encoding?

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#100]
I generated an environment file with those chars in my password: `ù` and `§`. They are dropped in the end when then .env file is generated.
That's a problem since we loose some chars and the connection to the DB is then broken.

Find out how to increase support for those chars.

The ultimate solution would be to forbid some chars but that's not what we'd like.

**Comment by Besfr** [comment]
The issue could be the usage of escapeshellarg that strip non-ASCII char.
There is some comments in the doc page https://www.php.net/manual/fr/function.escapeshellarg.php about that or some fixes to test in the wild : https://markushedlund.com/dev/php-escapeshellarg-with-unicodeutf-8-support/

**Comment by Artusamak** [comment]
`Escape::shellArg()` from `consolidation/site-process` should do the work. 

Blocked by #70 to fully test.

**Comment by Artusamak** [comment]
For a side test, i confirm that it works, the output is well protected and escaped.
