### ISSUE TITLE
Implement a way to know if our .env file should be updated

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#11]
Sometimes, we need to add project specific variables to the settings.sh/.combawa file.
In this scenario, a person that would pull a new version of this file could not know that they have to update their .env file accordingly.

Proposed solution: add a COMBAWA_SCHEMA variable which value is 1 by default in both settings.sh/.combawa and .env files. In the prerequisites, check that these numbers are equal.

**Do not forget to document this change in the readme**

**Comment by Artusamak** [comment]
Duplicates #9 ? ;)

**Comment by DuaelFr** [comment]
Closed as duplicate
