### ISSUE TITLE
Let me ignore a parameter when i generate an environment

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#14]
When I initialize my `.env`, i'd like to be able to ignore some parameters.

Take this use case as an example: i'm running the generate env command on a staging environment, i may want to follow the config defined in the settings.sh file and not force a specific build mode. As is, i must override it in my `.env`. By doing so, i loose the ability to let the dev team trigger the switch from install to update on all environments.

It also happens that installing `prod` is a special use case where all questions doesn't prompt. We may want to always ask all questions and show the default from settings.sh if define and offer to override or not each parameter.

**Comment by Artusamak** [comment]
After more digging, this isn't relevant for the build mode because it's not collected by the interactive installer.

The consistency in the collected parameters still make sense though.

Use case : i install my future prod on my preprod server in order to prepare the content. I want to install in prod mode but my URL will change when i move the install to the new server.

**Comment by DuaelFr** [comment]
See #17 
I think we need to reconsider our environments names and purposes :)

**Comment by Artusamak** [comment]
Leaner version: i may want the value of a `.env` setting to follow the value defined in the `settings.sh` file. At the moment it's not possible, with the interactive command i must provide a value.  
We could improve this by fetching the default value, show it during the interactive command and if the user doesn't change the value, ignore the setting in the `.env` file generation.

We agree on the feature request, it's just painful to implement. :)

**Comment by Artusamak** [comment]
This doesn't seem a relevant issue anymore. If you want to install with a specific mode in an env, you can override --env argument.
