### ISSUE TITLE
Add function "fetch only"

### ISSUE THREAD

**Issue by denics** [Happyculture/combawa#16]
It might happen that we need to launch combawa only to fetch the db. I can see this scenario in a CI where we need to collect the DB, do some operations, then launch combawa.

**Comment by Artusamak** [comment]
Since the fetch DB operation is just an `scp`, why not `scp` directly in your CI?

**Comment by denics** [comment]
because you already define the necessary variables in the .env and you do not have to declare again the same values in CI (that can lead to security issues in certain cases)

**Comment by Artusamak** [comment]
This is not the package purpose to only be used to fetch dumps.
