### ISSUE TITLE
Reconsider environment names and purposes

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#17]
We currently have 4 different environments (dev, preprod, recette, prod) in combawa which are, in my opinion, unclear and not covering the common use cases.

I think we should use th following ones:

- dev: (unchanged) environment used to check if everything builds properly
  - all dev tools enabled
  - database crushed and dummy data generated if needed
- testing: environment used to validate developments
  - no dev tools enabled
  - database crushed and dummy data generated if needed
- preprod: environment used to prepare production and validate the developments on the target server.
  - no dev tools enabled
  - should be as close as prod as possible but with some possible environment overrides (mainly URL)
  - files and database preserved (but should be loaded from real prod by an external process)
- prod: well... production
  - no dev tools enabled
  - minimal settings
  - files and database preserved

**Comment by Artusamak** [comment]
We discussed this and considered that it could be a BC breaker. 
We might need to open 9.x to do this change.

**Comment by Artusamak** [comment]
After discussion, we identified only 3 environments that are relevant:

- dev: which is the local env for any developer and that can be used in CI
- testing: which is usable in CI without any dev modules and where you can disable or enable caching modules, use a specific split to enable URL based API endpoints, prevent mail sending...
- prod: which is the prod and the default build scenario.

"Recette" and "testing" exist at the moment and are always similar in the current templates, we will squash them. If one day you need a new env, please open an issue for us to discuss it.

**Comment by Artusamak** [comment]
It is now squashed.
