### ISSUE TITLE
Support local copy to retrieve the reference dump

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#23]
If you don't want to version the reference dump, it may be kind to easy its recuperation.
As of today you must use `scp` but if your dump is fetch by some scripts somewhere else on your server, it would be kind to be able to use `cp` to fetch it.

**Comment by Artusamak** [comment]
The attach commit tries to use cp if the `COMBAWA_SSH_CONFIG_NAME` variable is empty. 
An improvement could be to also test if the source file of the `cp` exists.

**Comment by DuaelFr** [comment]
It looks like it's been done :)
