### ISSUE TITLE
Remove dependency to the reference dump

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#3]
As is, we require the usage of the reference dump. It would reduce the friction for adoption if this step was optional? At least when using the generate environment command, if a user doesn't have this dump, it's a mystery to figure out what this option does.

**Comment by Artusamak** [comment]
There also the install phase where using a dump doesn't make sense.

Option: using the install mode (no questions related to dumps), then having a command to switch to update mode that prompts to ask how to fetch the reference dump (remote, local, etc) [Related  to #33-665007734 for this part].

**Comment by DuaelFr** [comment]
We decided to go for the #33 version.
