### ISSUE TITLE
Give a chance to version prod config overrides

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#36]
When i fetch a dump from the prod site, i have no way to check if the features / config have been overriden in prod. It may lead to data loss (or at least configuration losses) since the overrides are lost as soon as the `drush fra`  / `drush cim`  command is run.

We should have an flag / option to let the user install the site with the overrides and let him/her export/dismiss the changes.

**Comment by Artusamak** [comment]
Version 0 of this is to stop after importing the dump and let the dev decide what to do next.

**Comment by Artusamak** [comment]
Version 0 implemented. We can stop here. Let's discuss it.

**Comment by Artusamak** [comment]
@DuaelFr I'll let you decide if we want to go further on this.

**Comment by DuaelFr** [comment]
Looks good to me.
