### ISSUE TITLE
Make it Drupal 9 ready

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#39]
There is probably not a lot to do to make it compatible with Drupal 9.
Project build should be exactly the same.
Project generation might need some minor changes.

**Comment by Artusamak** [comment]
We may want to simplify the core version folder templates that are almost always identical. It would make it easier to maintain. (even more if we drop Drupal 7 support).

**Comment by DuaelFr** [comment]
Seem to be blocked by https://github.com/hechoendrupal/drupal-console/issues/4250

**Comment by DuaelFr** [comment]
Last alpha works with D9 without issues.
