### ISSUE TITLE
Move the download/load_dump mecanism out of the predeploy

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#42]
Add an env var and a parameter to enable/disable this.
Disabled this by default for prod environment. Enable this by default for all other environments.

**Comment by Artusamak** [comment]
Done with the -r argument. Doc needs to be updated and fetch tested on a real project.

**Comment by Artusamak** [comment]
It works! Reworded as "reimport" instead of "reinstall" to be more accurate.
