### ISSUE TITLE
Review and update variable names for clarity and consistency

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#46]
List of existing variables we could keep without modification:

- COMBAWA_PROJECT_NAME
- COMBAWA_PROJECT_MACHINE_NAME
- COMBAWA_BUILD_MODE
- COMBAWA_WEBSITE_URI
- COMBAWA_DB_HOSTNAME
- COMBAWA_DB_PORT
- COMBAWA_DB_DATABASE
- COMBAWA_DB_USER
- COMBAWA_DB_PASSWORD

List of existing variables that could be changed:

- COMBAWA_ENV => **COMBAWA_BUILD_ENV**
To improve consistency with COMBAWA_BUILD_MODE and because it's only used in the build process.

- COMBAWA_BACKUP_BASE => **COMBAWA_BACKUP_DB_ENABLED**
- COMBAWA_FETCH_DB_DUMP => **COMBAWA_FETCH_DB_ENABLED**
All 1/0 flags should have the same suffix to indicate what they are for.

- COMBAWA_SSH_CONFIG_NAME => **COMBAWA_FETCH_DB_SCP_PREFIX**
- COMBAWA_PROD_DB_DUMP_PATH => **COMBAWA_FETCH_DB_SCP_PATH**
Those two vars are used in the same context so they should share the same namespace.
Beware, if COMBAWA_SSH_CONFIG_NAME is empty, the COMBAWA_PROD_DB_DUMP_PATH is used with a simple `cp` instead of a `scp`. Proposed names can be confusing. => to be discussed 

- COMBAWA_DUMP_FILE_NAME
I don't like this one :rofl:

**Comment by Artusamak** [comment]
I'm ok to rename variables. One remark though, i disagree with the "enabled" suffix for variables that are toggles. We may reword with verbs but not "enabled".

I most of the time add "FLAG" in the name of my PHP variables. Would it work for you?  


COMBAWA_BACKUP_BASE => COMBAWA_BACKUP_DB_ENABLED => **COMBAWA_FLAG_DB_GEN_BACKUP**?
COMBAWA_FETCH_DB_DUMP => COMBAWA_FETCH_DB_ENABLED => **COMBAWA_FLAG_DB_FETCH_DUMP**?

COMBAWA_SSH_CONFIG_NAME => COMBAWA_FETCH_DB_SCP_PREFIX => **COMBAWA_FETCH_REMOTE_CNX_STRING**?
COMBAWA_PROD_DB_DUMP_PATH => COMBAWA_FETCH_DB_SCP_PATH => **COMBAWA_FETCH_REMOTE_PATH**?

The SSH variables will have to be reworked based on #48 

> COMBAWA_DUMP_FILE_NAME

Can you detail what you don't like in its name?

**Comment by DuaelFr** [comment]
I'm ok with the usage of "FLAG" instead of "ENABLED" if you prefer.
I'd like to keep it at the end of the name, though. This way, variables can be easily sorted by prefix to have something that looks like a namespace.

Here are my proposals:
- COMBAWA_DB_BACKUP_FLAG
- COMBAWA_DB_FETCH_FLAG
- COMBAWA_DB_FETCH_(REMOTE_)CNX_STRING
- COMBAWA_DB_FETCH_(REMOTE_)PATH

(I think the `REMOTE_` part can be dropped to have shorter names but I let you choose this)

> > COMBAWA_DUMP_FILE_NAME
>
> Can you detail what you don't like in its name?

I don't like it because it's not linked with other names and it does not explain itself either. The more I think about this variable, the more I think we might just remove it. I'll open another issue to discuss this particular idea.

**Comment by Artusamak** [comment]
Done.
