### ISSUE TITLE
The build mode isn't collected

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#5]
When running `drupal combawa:generate-environment` the build mode isn't collected. If you run the command, answer to each question and then run combawa, you end up with a failure due to the fact that the build mode isn't collected.

**Comment by DuaelFr** [comment]
Build mode hasn't been collected here on purpose. It should not differ between environments.
Why would you need it?

**Comment by Artusamak** [comment]
It's not because it shouldn't differ that it shouldn't be collected. If you start from scratch the settings.sh file isn't populated with the correct information so you can't build the app.

**Comment by DuaelFr** [comment]
Why would you want to build the app before having generated it?
Combawa cannot run without a settings.sh file and it suggests to run `drupal combawa:generate-project` to initialize it. I cannot see any use case where we could have a settings.sh file without build mode.

**Comment by Artusamak** [comment]
Hmm, you're correct, the issue might have been opened without running the generate build command first. :thinking: 

Let's close for now.
