### ISSUE TITLE
Add --no-predeploy --no-postdeploy options

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#50]
Because we are very cool, we want to allow the users to fasten their rebuilds. If they know that a predeploy or postdeploy doesn't need to be run, we can add extra options to avoid to steps to be run.

$100000 question: In which direct doesn't the option makes more sense? Do we want to skip the step or do we want to run it only.

I sense that we may need --only-predeploy more that --no-predeploy. (Do we need both?!)

Use cases that may influence our decision:  
- I need to test my predeploy actions / postdeploy actions, how can i do that fast?

**Comment by Artusamak** [comment]
@DuaelFr Your opinion is kindly requested here!

**Comment by DuaelFr** [comment]
Both would be awesome!

**Comment by Artusamak** [comment]
Now we have both! :)
