### ISSUE TITLE
Consider removing COMBAWA_PROD_DB_DUMP_PATH

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#52]
Currently, the `COMBAWA_PROD_DB_DUMP_PATH` variable allows to reference a local dump file or to choose the name of the dump file that will be fetched from a remote server. The fetch method allow to use a local path by leaving the connexion string empty. Thus, we don't need `COMBAWA_PROD_DB_DUMP_PATH` anymore and we can replace it by a random location in the `/tmp` folder.

**Comment by Artusamak** [comment]
Please wait for #33 to be done to act on this one.

**Comment by Artusamak** [comment]
My missing piece of the puzzle => we can deduce the file name from the connection string.

I still need to decide if we can remove the variable at all or not. Even if we don't collect this value from the user, we will have to carry the dump name in a variable.

**Comment by DuaelFr** [comment]
I'm good with an internal variable. We would not need to collect it anymore which would be great!

**Comment by Artusamak** [comment]
This is now a computed variable.

**Comment by Artusamak** [comment]
There is a followup with #54 and we need to document that only gzip are supported at the moment. Issue incoming.

Both done.
