### ISSUE TITLE
Reconsider .combawa VS .env

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#60]
We have settings in the .combawa that doesn't make sense because they are different if you are in install or update mode.

Eg: COMBAWA_DB_BACKUP_FLAG => This setting doesn't make sense in install mode.

Plus it's duplicated if we run combawa.sh with explicit arguments that can override those settings.

We need to reevaluate if the .combawa file still makes sense and what should remain in it.

**Comment by DuaelFr** [comment]
IMHO, some things are related to the project (name, build mode) and some other are related to the environment (db settings, fetch mode).
The original idea was that wanted to be able to we shouldn't need a .env file on the production environment. We also wanted those base settings to be commited so the repository would be the reference point. The goal was to set the environment once at the beginning of the project and keep it unless some important change had to be done. In my experience, it works well for now :)

**Comment by DuaelFr** [comment]
Given #67, it has been decided that .combawa was not necessary anymore.
