### ISSUE TITLE
Do not ask to define COMBAWA_DUMP_FILE_NAME anymore

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#65]
We should calculate the value of `COMBAWA_DUMP_FILE_NAME` instead of asking the user to define it.
To let the user fetch the dump once and reimport it more, the dump location and name should not be randomized.
The suggested value is `/tmp/combawa/project_name.sql.gz`

**Comment by Artusamak** [comment]
Done, i did not set it to tmp since it's a file that we want to preserve as long as needed. I placed it in /dumps.
