### ISSUE TITLE
Check that the COMBAWA_WEBROOT_PATH stored variable is generated properly

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#66]
This var is not stored anymore (`.combawa` file is gone)
It might need to be reintroduced somehow (maybe extracted from composer.json)

**Comment by Artusamak** [comment]
Let's fetch the value in the cge command and add a default value to /web

**Comment by denics** [comment]
Is there a way this can be ported to 8?

**Comment by DuaelFr** [comment]
Current state of Combawa is that `COMBAWA_WEBROOT_PATH` is generated using `DrupalFinder::getDrupalRoot()` which is good **but** `COMBAWA_WEBROOT_PATH` is never used anywhere…

We could start using it but I don't like having this value saved in the `.env` file and I don't know how we could calculate it on the fly. Any thoughts @Artusamak ?

**Comment by Artusamak** [comment]
Let's remove it and rollback if someone cries :D

**Comment by DuaelFr** [comment]
TODO : remove this var
