### ISSUE TITLE
Rework ibs command

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#67]
During our thinking process, we decided that 
- some variables were not needed anymore
- some were only useful as metadata, not as environment variables
- some could be replaced by smart defaults instead of living in the `.combawa` file

A a result, we have to do the following changes:
- do not collect the project name anymore
- store the project machine name and the build mode in the `composer.json` file (extras > combawa)
- do not generate the `.combawa` file anymore

**Comment by Artusamak** [comment]
We are just missing to remove the --uri flag from documentation
