### ISSUE TITLE
Add variables checks during the prerequisites step

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/combawa#68]
These variables are now mandatory, check if they are set before running the script:
- build mode (currently in `.combawa`, soon in `composer.json`)
- build env
- database settings
- ~~db fetch command (if build mode is "update" only)~~

If one of them is missing, ask the user to run the appropriate command to generate them.

**Comment by Artusamak** [comment]
Done for the db fetch (only if you try to fetch instead of checking for the update mode).

**Comment by DuaelFr** [comment]
Added build mode test
Fixed db settings test
Build env test is no longer needed as we have a smart default to 'prod'
