### ISSUE TITLE
Remove dependency to npm

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#7]
Having to require NPM in the build process is probably not a good idea if you operate with a lightweight process or wants to build just the prod sites. Requiring NPM to build the CSS is overkilled. Just being able to plug to it if you want to compile the theme seems like a smoother approach.

**Comment by DuaelFr** [comment]
Npm dependency has been removed.
Npm builds should to be ran out of combawa from now.

**Comment by Artusamak** [comment]
It's a good start but it lacks a documentation for actual installations i think. I could throw a curse word like BC but i won't =).

**Comment by Artusamak** [comment]
#11

**Comment by DuaelFr** [comment]
To be discussed in #9
