### ISSUE TITLE
SSH and SCP have different arguments for Proxy Jump

### ISSUE THREAD

**Issue by denics** [Happyculture/combawa#83]
ATM Combawa try to check that the SSH connection works using the ``COMBAWA_SSH_CONFIG_NAME`` env variable and then, it uses the same variable to start the SCP session.

However, a problem arise if we have to use the *ProxyJump* feature, that allow to use a tunnel in one machine to download from a third one (i.e. you have access to a secure front to connect to a DMZ). SSH and SCP, for historical reasons, have different arguments to define ProxyJump so a solution could be to simply use SSH and copy using:

```
ssh $COMBAWA_SSH_CONFIG_NAME "cat $COMBAWA_PROD_DB_DUMP_PATH" > "$APP_ROOT/$COMBAWA_DUMP_FILE_NAME.gz"
```

**Comment by Artusamak** [comment]
Please try the >9.0.0-beta2 version that rewrites scp / cp commands management.

**Comment by denics** [comment]
but combawa 9 is not compatible with D7 :(
