### ISSUE TITLE
Ease life: Help stage file proxy generate new image styles directories

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#85]
If you are on a site where stage file proxy is enabled and create a new image style for an image coming though stage file proxy, you'll end up with no image / a broken image / an incorrect image sizes.

This is due to the fact that the source derivated image doesn't exist (yet) in prod.

One way to mitigate that could be to precreate the image style directory on the test site to generate the image. (This is an idea to test).
Pain point, iterating over config to identify the directories to create.

**Comment by DuaelFr** [comment]
Is it the job of Combawa?

**Comment by Artusamak** [comment]
Probably not core.

**Comment by Artusamak** [comment]
Reject.
