### ISSUE TITLE
Test as standalone

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#89]
Last but not least task, verify that Combawa is working without any HC specific.

Evaluate if drupal console is a --dev dependency or a --prod dependency. We need it to generate any template file, i think it's required as a --prod dependency.

TODO:
- [x] Find out how to deliver load.environment.php
- [x] Find our how to deliver the required snippet for composer autoloader (see below)

Autoloader snipper :

```
    "autoload": {
        "files": ["load.environment.php"]
    },
```

**Comment by DuaelFr** [comment]
I suppose `composer project:build -- -m update` is not enough? :)

**Comment by Artusamak** [comment]
I'd say, start a project from drupal doc https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates

Then try to plug combawa from this starting point.

**Comment by DuaelFr** [comment]
I totally wrote that in the wrong issue :D
I'll work on this issue on thursday.

**Comment by Artusamak** [comment]
If we define it within Combawa composer.json it works <3

**Comment by Artusamak** [comment]
Meh, back to square one.

**Comment by Artusamak** [comment]
Adjusting the load.environment.php did the trick! :muscle:
