### ISSUE TITLE
Switch update mode and machine name in IBS command

### ISSUE THREAD

**Issue by Artusamak** [Happyculture/combawa#90]
The ibs command ask for a machine name and then the build mode. If you are in update mode, it doesn't make sense, the project machine name is useless. 

We should switch the parameters and only collect the machine name if we are in install mode.

**Comment by Artusamak** [comment]
It's updated. We may reconsider the variable name, it's only used for the installation profile name, we should probably reflect that.

**Comment by DuaelFr** [comment]
The machine name is never used by any of our tools. I'll drop its collection and move the composer.json name change to kumquat.

**Comment by Artusamak** [comment]
Please revert this change, the machine name is used in the install.sh script.

**Comment by DuaelFr** [comment]
Ooops!
All right, reverted ;)

**Comment by DuaelFr** [comment]
Variable renamed. All done here!
